services:
    light_saml_sp.credential.credential_store:
        class: LightSaml\Store\Credential\CompositeCredentialStore
        factory: [@light_saml_sp.credential.credential_store_factory, build]
        arguments:
            - @light_saml_sp.party.idp_entity_descriptor_store
            - @light_saml_sp.party.sp_entity_descriptor_store
            - "@=service('light_saml_sp.own.credential_store').getByEntityId(%light_saml_sp.own.entity_id%)"
            - []

    light_saml_sp.credential.credential_store_factory:
        class: LightSaml\Store\Credential\Factory\CredentialFactory
