parameters:
    light_saml_sp.own.entity_id: ~

services:
    light_saml_sp.own.credential_store:
        class: LightSaml\Store\Credential\StaticCredentialStore

    light_saml_sp.own.entity_descriptor_provider:
        class: LightSaml\Provider\EntityDescriptor\EntityDescriptorProviderInterface
        factory: [LightSaml\Provider\EntityDescriptor\FileEntityDescriptorProviderFactory, fromEntityDescriptorFile]

