services:
    light_saml_sp.store.name_id_validator:
        class: LightSaml\Validator\Model\NameId\NameIdValidator

    light_saml_sp.store.statement_validator:
        class: LightSaml\Validator\Model\Statement\StatementValidator

    light_saml_sp.store.subject_validator:
        class: LightSaml\Validator\Model\Subject\SubjectValidator
        arguments:
            - @light_saml_sp.store.name_id_validator

    light_saml_sp.store.assertion_time_validator:
        class: LightSaml\Validator\Model\Assertion\AssertionTimeValidator

    light_saml_sp.store.assertion_validator:
        class: LightSaml\Validator\Model\Assertion\AssertionValidator
        arguments:
            - @light_saml_sp.store.name_id_validator
            - @light_saml_sp.store.subject_validator
            - @light_saml_sp.store.statement_validator

    light_saml_sp.store.endpoint_resolver.binding:
        class: LightSaml\Resolver\Endpoint\BindingEndpointResolver

    light_saml_sp.store.endpoint_resolver.descriptor_type:
        class: LightSaml\Resolver\Endpoint\DescriptorTypeEndpointResolver

    light_saml_sp.store.endpoint_resolver.service_type:
        class: LightSaml\Resolver\Endpoint\ServiceTypeEndpointResolver

    light_saml_sp.store.endpoint_resolver.index:
        class: LightSaml\Resolver\Endpoint\IndexEndpointResolver

    light_saml_sp.store.endpoint_resolver.location:
        class: LightSaml\Resolver\Endpoint\LocationEndpointResolver

    light_saml_sp.store.endpoint_resolver:
        class: LightSaml\Resolver\Endpoint\CompositeEndpointResolver
        calls:
            - [add, [@light_saml_sp.store.endpoint_resolver.binding]]
            - [add, [@light_saml_sp.store.endpoint_resolver.descriptor_type]]
            - [add, [@light_saml_sp.store.endpoint_resolver.service_type]]
            - [add, [@light_saml_sp.store.endpoint_resolver.index]]
            - [add, [@light_saml_sp.store.endpoint_resolver.location]]

    light_saml_sp.store.binding_factory:
        class: LightSaml\Binding\BindingFactory
        arguments:
            - @light_saml_sp.system.event_dispatcher

    light_saml_sp.store.credential_resolver_factory:
        class: LightSaml\Resolver\Credential\Factory\CredentialResolverFactory
        arguments:
            - @light_saml_sp.credential.credential_store

    light_saml_sp.store.credential_resolver:
        class: LightSaml\Resolver\Credential\CompositeFilterResolver
        factory: [@light_saml_sp.store.credential_resolver_factory, build]

    light_saml_sp.store.signature_resolver:
        class: LightSaml\Resolver\Signature\OwnSignatureResolver
        arguments:
            - @light_saml_sp.store.credential_resolver

    light_saml_sp.store.signature_validator:
        class: LightSaml\Validator\Model\Signature\SignatureValidator
        arguments:
            - @light_saml_sp.store.credential_resolver

    light_saml_sp.store.session_processor:
        class: LightSaml\Resolver\Session\SessionProcessor
        arguments:
            - @light_saml_sp.store.sso_state
            - @light_saml_sp.system.time_provider
