parameters:
    lightsaml_sp.route.discovery: lightsaml_sp.discovery
    lightsaml.route.login_check: lightsaml_sp.login_check

services:
    light_saml_sp.username_mapper.simple:
        class: LightSaml\SpBundle\Security\User\SimpleUsernameMapper
        arguments:
            - []
